.PHONY: clean All

All:
	@echo "----------Building project:[ 2016-2017-V2CPSE1-06-91-compressor-decompressor - Debug ]----------"
	@cd "2016-2017-V2CPSE1-06-91-compressor-decompressor" && "$(MAKE)" -f  "2016-2017-V2CPSE1-06-91-compressor-decompressor.mk"
clean:
	@echo "----------Cleaning project:[ 2016-2017-V2CPSE1-06-91-compressor-decompressor - Debug ]----------"
	@cd "2016-2017-V2CPSE1-06-91-compressor-decompressor" && "$(MAKE)" -f  "2016-2017-V2CPSE1-06-91-compressor-decompressor.mk" clean
