.PHONY: clean All

All:
	@echo "----------Building project:[ 2016-2017-V2CPSE1-02-01-max -  ]----------"
	@cd "2016-2017-V2CPSE1-02-01-max" && "$(MAKE)" -f  "2016-2017-V2CPSE1-02-01-max.mk"
clean:
	@echo "----------Cleaning project:[ 2016-2017-V2CPSE1-02-01-max -  ]----------"
	@cd "2016-2017-V2CPSE1-02-01-max" && "$(MAKE)" -f  "2016-2017-V2CPSE1-02-01-max.mk" clean
