.PHONY: clean All

All:
	@echo "----------Building project:[ week-4 -  ]----------"
	@cd "week-4" && "$(MAKE)" -f  "week-4.mk"
clean:
	@echo "----------Cleaning project:[ week-4 -  ]----------"
	@cd "week-4" && "$(MAKE)" -f  "week-4.mk" clean
